version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_USERNAME=$DATABASE_USERNAME
      - MONGO_PASSWORD=$DATABASE_PASSWORD
      - MONGO_HOST=db
      - MONGO_PORT=$DATABASE_PORT
      - MONGO_DB=$DATABASE
    ports:
      - '3000:3000'
    networks:
      - todo-network
    links:
      - mongo
  mongo:
    image: mongo
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_ROOT_PASSWORD
      - MONGO_INITDB_DATABASE=$DATABASE
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - MONGO_PORT=$DATABASE_PORT
    volumes:
      - /home/s0n1c/tmp/db:/data/db
      - ./docker_scripts/:/docker-entrypoint-initdb.d
    # ports:
    # - 27017:27017
    networks:
      - todo-network
networks:
  todo-network:
    driver: bridge
